# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lean with mathlib - first project
email: Gravifer@users.noreplygithub.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal first project with Lean and mathlib.
  All is for learning purposes.
baseurl: "/lean-mathlib-1stproj" # the subpath of your site, e.g. /blog
url: "https://gravifer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  Gravifer

# Repository information for GitHub Pages
repository: Gravifer/lean-mathlib-1stproj

# Build settings
theme: just-the-docs # minima
plugins:
  - jekyll-feed

# just-the-docs theme configuration
aux_links:
  "Project Repository":
    - "//github.com/Gravifer/lean-mathlib-1stproj"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Gravifer/lean-mathlib-1stproj"
gh_edit_branch: "main"
gh_edit_source: home_page
gh_edit_view_mode: "tree"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
